"""initial schema

Revision ID: 4028e416c123
Revises: 
Create Date: 2026-08-04 18:20:11.897962

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4028e416c123'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_rules_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_rules_configs'))
    )
    op.create_index('uq_business_rules_configs_one_active', 'business_rules_configs', ['is_active'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('suppliers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('code', name=op.f('uq_suppliers_code')),
    sa.UniqueConstraint('name', name=op.f('uq_suppliers_name'))
    )
    op.create_table('unit_lookup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_unit', sa.String(), nullable=False),
    sa.Column('normalized_unit', sa.String(), nullable=False),
    sa.Column('units_per_case', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('multiplier_confirmed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit_lookup')),
    sa.UniqueConstraint('raw_unit', name=op.f('uq_unit_lookup_raw_unit'))
    )
    op.create_table('list_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('source_file_s3_key', sa.String(), nullable=False),
    sa.Column('source_file_original_filename', sa.String(), nullable=False),
    sa.Column('source_file_type', sa.Enum('EXCEL', 'CSV', 'PDF', name='source_file_type'), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'MAPPING_PENDING', 'MAPPING_CONFIRMED', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='list_run_status'), nullable=False),
    sa.Column('proposed_column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmed_column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('column_mapping_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('column_mapping_confirmed_by', sa.String(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_rows', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_list_runs_supplier_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_list_runs'))
    )
    op.create_table('product_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('supplier_item_number', sa.String(), nullable=False),
    sa.Column('asin', sa.String(), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('match_status', sa.Enum('PROPOSED', 'CONFIRMED', 'REJECTED', name='match_status'), nullable=False),
    sa.Column('match_source', sa.Enum('AUTO', 'MANUAL', name='match_source'), nullable=False),
    sa.Column('confirmed_by', sa.String(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_product_matches_supplier_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_matches')),
    sa.UniqueConstraint('supplier_id', 'supplier_item_number', name='uq_product_matches_supplier_item')
    )
    op.create_table('raw_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('list_run_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supplier_item_number', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('case_quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('case_unit_raw', sa.String(), nullable=True),
    sa.Column('case_unit_normalized', sa.String(), nullable=True),
    sa.Column('item_type', sa.Enum('STANDARD', 'DISPLAY_BUNDLE', 'TIERED_PROMO', 'AMBIGUOUS', name='line_item_type'), nullable=False),
    sa.Column('parse_status', sa.Enum('OK', 'NEEDS_REVIEW', 'ERROR', name='parse_status'), nullable=False),
    sa.Column('parse_notes', sa.Text(), nullable=True),
    sa.Column('product_match_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_run_id'], ['list_runs.id'], name=op.f('fk_raw_line_items_list_run_id')),
    sa.ForeignKeyConstraint(['product_match_id'], ['product_matches.id'], name=op.f('fk_raw_line_items_product_match_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_line_items')),
    sa.UniqueConstraint('list_run_id', 'row_number', name='uq_raw_line_items_run_row')
    )
    op.create_table('amazon_data_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('list_run_id', sa.UUID(), nullable=False),
    sa.Column('raw_line_item_id', sa.UUID(), nullable=False),
    sa.Column('asin', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('buy_box_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('buy_box_owner', sa.String(), nullable=True),
    sa.Column('amazon_has_buy_box', sa.Boolean(), nullable=True),
    sa.Column('referral_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fba_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('other_fees', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_monthly_sales', sa.Integer(), nullable=True),
    sa.Column('sales_rank', sa.Integer(), nullable=True),
    sa.Column('sales_rank_category', sa.String(), nullable=True),
    sa.Column('seller_count', sa.Integer(), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=True),
    sa.Column('is_gated', sa.Boolean(), nullable=True),
    sa.Column('gated_approval_status', sa.Enum('NOT_APPLICABLE', 'APPROVED', 'PENDING_APPROVAL', 'NOT_APPROVED', name='gated_approval_status'), nullable=False),
    sa.Column('manufacturer_sells_directly', sa.Boolean(), nullable=True),
    sa.Column('sp_api_raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keepa_raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_run_id'], ['list_runs.id'], name=op.f('fk_amazon_data_snapshots_list_run_id')),
    sa.ForeignKeyConstraint(['raw_line_item_id'], ['raw_line_items.id'], name=op.f('fk_amazon_data_snapshots_raw_line_item_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amazon_data_snapshots'))
    )
    op.create_table('manual_review_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('list_run_id', sa.UUID(), nullable=False),
    sa.Column('raw_line_item_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('LOW_CONFIDENCE_MATCH', 'DISPLAY_BUNDLE_SKU', 'TIERED_PROMO_PRICING', 'GATED_PENDING_STRONG_DEAL', 'AMBIGUOUS_PARSE', 'OTHER', name='review_reason'), nullable=False),
    sa.Column('reason_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'DISMISSED', name='review_status'), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['list_run_id'], ['list_runs.id'], name=op.f('fk_manual_review_queue_list_run_id')),
    sa.ForeignKeyConstraint(['raw_line_item_id'], ['raw_line_items.id'], name=op.f('fk_manual_review_queue_raw_line_item_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_review_queue')),
    sa.UniqueConstraint('raw_line_item_id', name=op.f('uq_manual_review_queue_raw_line_item_id'))
    )
    op.create_table('classification_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('list_run_id', sa.UUID(), nullable=False),
    sa.Column('raw_line_item_id', sa.UUID(), nullable=False),
    sa.Column('amazon_data_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('rules_config_id', sa.UUID(), nullable=True),
    sa.Column('classification', sa.Enum('BUY', 'REVIEW', 'NEGOTIATE', 'NO_BUY', 'HIGH_RISK', name='classification_label'), nullable=False),
    sa.Column('roi', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('margin', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('rule_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['amazon_data_snapshot_id'], ['amazon_data_snapshots.id'], name=op.f('fk_classification_results_amazon_data_snapshot_id')),
    sa.ForeignKeyConstraint(['list_run_id'], ['list_runs.id'], name=op.f('fk_classification_results_list_run_id')),
    sa.ForeignKeyConstraint(['raw_line_item_id'], ['raw_line_items.id'], name=op.f('fk_classification_results_raw_line_item_id')),
    sa.ForeignKeyConstraint(['rules_config_id'], ['business_rules_configs.id'], name=op.f('fk_classification_results_rules_config_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_classification_results')),
    sa.UniqueConstraint('raw_line_item_id', name=op.f('uq_classification_results_raw_line_item_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classification_results')
    op.drop_table('manual_review_queue')
    op.drop_table('amazon_data_snapshots')
    op.drop_table('raw_line_items')
    op.drop_table('product_matches')
    op.drop_table('list_runs')
    op.drop_table('unit_lookup')
    op.drop_table('suppliers')
    op.drop_index('uq_business_rules_configs_one_active', table_name='business_rules_configs', postgresql_where=sa.text('is_active'))
    op.drop_table('business_rules_configs')
    # ### end Alembic commands ###

    # Not auto-generated: op.drop_table() does not drop the Postgres native
    # ENUM types those columns used (CREATE TYPE / DROP TYPE are separate
    # objects from the table). Without this, `downgrade` then `upgrade`
    # fails with "type already exists" - confirmed by actually running that
    # cycle against local Postgres while verifying this migration. Order
    # doesn't matter here since all owning tables are already gone above.
    for enum_name in (
        "classification_label",
        "review_status",
        "review_reason",
        "gated_approval_status",
        "match_source",
        "match_status",
        "parse_status",
        "line_item_type",
        "list_run_status",
        "source_file_type",
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
