"""add sales_rank_drops to amazon_data_snapshots

Revision ID: 76fe4e403190
Revises: 4028e416c123
Create Date: 2026-08-06 14:33:44.052876

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fe4e403190'
down_revision: Union[str, None] = '4028e416c123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amazon_data_snapshots', sa.Column('sales_rank_drops_30d', sa.Integer(), nullable=True))
    op.add_column('amazon_data_snapshots', sa.Column('sales_rank_drops_90d', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amazon_data_snapshots', 'sales_rank_drops_90d')
    op.drop_column('amazon_data_snapshots', 'sales_rank_drops_30d')
    # ### end Alembic commands ###
