"""add ambiguous_restriction to amazon_data_snapshots and review_reason enum

Revision ID: e64eb0eeb98c
Revises: 76fe4e403190
Create Date: 2026-08-15 15:48:23.771343

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e64eb0eeb98c'
down_revision: Union[str, None] = '76fe4e403190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amazon_data_snapshots', sa.Column('ambiguous_restriction', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # Autogenerate doesn't detect new members on an existing Postgres
    # native ENUM type (only column diffs) - added by hand. Safe to run
    # inside this transaction on Postgres 12+ (this project runs 16) as
    # long as the new value isn't used in the same transaction, which it
    # isn't here. See docs/decisions/0002-database-schema-decisions.md for
    # the related note on this project's other native-ENUM migration quirk
    # (autogenerated downgrade() not dropping the type itself).
    op.execute("ALTER TYPE review_reason ADD VALUE IF NOT EXISTS 'ambiguous_restriction'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amazon_data_snapshots', 'ambiguous_restriction')
    # ### end Alembic commands ###

    # Postgres has no DROP VALUE for enum types - removing
    # 'ambiguous_restriction' from review_reason would require rebuilding
    # the type (rename old, create new, migrate column, drop old), not
    # worth doing for a downgrade path. Left as a known no-op, same
    # category as this project's other documented ENUM downgrade gap.
